travis:
  secure:
    BINSTAR_TOKEN: EoPacOb1j3Lrn55oPCpSdEphyxhnAfN5I/HSy7CEqVpGi46yJa0W7X6hHuFLUUeI+05/zBXvlrjTLPwNMvnWCSnHaySK8w7u4k/S6DSfD4CFX6c9lkV5MnYg8lC8iXszknc1Bu8cxYAhYmRnqv5PSVo64G5fMiRFsBDZ/z5MC4kWwYLRJfOgvv3sVn7cfhGaUOUXrf6mT23KXEX1zc3M19/LutD8bg/57Fm6qWHNAlgnQOFwRFUn3TO5FQwbJAm+v1MpN617dhxl0nPUrsZpVRzO2UWrSHmNm/uZAJC/EwR5EWster3IhkFjY0rwNJh9+y+FGU2r9nbAMqmgjaAo1N4Rs1iZ91g/G+jcevloUVcFL7ohvBKMeiqAqzGvlYd4fv7lEv+eickzUajTACtH2ow8ujOSgrzpgIL8x8AqWcwUEnVDoecnmX9l/SO71uHIvx7lb/Al+FbDG+NA2Z3MPLXv0GYGyAnCLR+A7u5naSZxUJl/b2I/3GMQ9OsStoLdI4DIGYRJwxU2EixyT68C8jjNTMRxbwk4xBvrVgT9Od9/BXqLHX0qQwztw16Ls9Qe51T8Co6bjW0nGrRc/PUx9rwNbL3CBM+jGntM+eP78D/G2clAbJYjeAdYpCsJ2pXsWgW7XEAZBtR8pQ2eY+wYVIkmYw++9YY8W+KcR6mID1E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
